### ISSUE TITLE
Do not limit cleverness of this lib to conf-env variables only

### ISSUE THREAD

**Issue by fracz** [akabekobeko/npm-cross-conf-env#15]
I believe the only thing that prevents us from using env variables in npm scripts is that normal OSs use `$[A-za-z0-9_-]+` and Windows uses `%[A-za-z0-9_-]+%`.

If your library wasn't limited to config variables only but would look for these patterns and adjust them according to the [detected OS](http://stackoverflow.com/questions/8683895/how-do-i-determine-the-current-operating-system-with-node-js) then it would solve the problem of cross-os replacment of environment variables in npm scripts, which is [dreamt feature](https://github.com/npm/npm/issues/10575) for [many people](https://github.com/npm/npm/issues/2800#issuecomment-225920998), including me.

Is it doable? Is there any problem I can't see with such solution?

**Comment by akabekobeko** [comment]
@fracz 

`cross-conf-env` is intended to be used the npm-scripts standard of variables (config field in `package.json`) in a cross-platform.

Therefore, it intended for those surrender prefix the `npm_package_` or `npm_config_` defined in `process.env`. If also other variables obtained from `process.env`, is also possible to the target of replacement.

Would that such support is that necessary?

**Comment by akabekobeko** [comment]
Close because it has been left for a long time.
