### ISSUE TITLE
Using a Config in a Redirect on Mac & Windows

### ISSUE THREAD

**Issue by elijahmanor** [akabekobeko/npm-cross-conf-env#17]
`cross-conf-env` has worked great for me when the command is self-contained, but if I try to redirect the output to a file that uses a conf it doesn't seem to work on Mac and Windows.

Other than creating a separate custom node script that manages all of that, is there something I am missing or some special syntax to do what I'm looking for?

```
"scripts": {
  "//": "The following only works on mac using $", 
  "build:worksOnMac": "mustache data.json src/index.mustache.js | uglifyjs > public/$npm_package_version/index.min.js",
  "//": "The following only work on windows using %", 
  "build:worksOnWindows": "mustache data.json src/index.mustache.js | uglifyjs > public/%npm_package_version%/index.min.js",
  "//": "The following should work on both, but since the config is in the redirect it doesn't not get updated", 
  "build:doesNotWork": "cross-conf-env mustache data.json src/index.mustache.js | uglifyjs > public/$npm_package_version/index.min.js",
  "//": "Any other ideas of what to try or CLI helpers to use?", 
  "//": "NOTE: I know I could write a custom node program, but I'm trying to see if there is another way",
  "build:anythingWorkInBoth": "echo I surely hope so...",
},
```

**Comment by akabekobeko** [comment]
There is a problem with the behavior of the reported sample because it is not a solution to npm_package_config in the pipeed command, `process.env` does not consider pipe.

Since it seems that the same report will continue in the future, it is described as a limitation in the `README.md`.
