### ISSUE TITLE
Using ':' between two variables not working on Windows 10 

### ISSUE THREAD

**Issue by yacovg** [akabekobeko/npm-cross-conf-env#25]
Those are not working under windows 10
"var": "cross-conf-env echo npm_package_version:npm_package_version"
"var": "cross-conf-env echo $npm_package_version:$npm_package_version"

npm run var
0.0.1:npm_package_version

This will work:
"var": "cross-conf-env echo %npm_package_version%:%npm_package_version%"

**Comment by akabekobeko** [comment]
It will be fixed by #30, so close it.
